#include <stdio.h>
#include "altera_up_avalon_video_pixel_buffer_dma.h"
#include "altera_up_avalon_video_character_buffer_with_dma.h"

#include "game_structs.h"
#include "graphics.h"

//initialize functions may be placed in another file as they are not strictly VGA related
//Function will initialize position and colour values for the baby graphics
void initialize_baby(int health, int bullet, int fire_rate, int body_pos[], int colour){

}

//Function will initialize position and colour values for the shark graphics
void initialize_shark(int type, int dmg, int health, int speed, int attack, int body_pos[], int colour){

}

//Function will initialize position and colour values for the cursor graphics
void initialize_cursor(int body_pos[], int state, int colour){

}

// Function will draw a baby image using info generated by the initialize function
void draw_baby(int body_pos[], int colour, alt_up_pixel_buffer_dma_dev* pixel_buffer){
	//draws baby's body
	alt_up_pixel_buffer_dma_draw_box(pixel_buffer, body_pos[0], body_pos[1], body_pos[2], body_pos[3], colour, 0);

}

// Function will draw a baby image using info generated by the initialize function

void draw_sharks(int body_pos[], int colour, alt_up_pixel_buffer_dma_dev* pixel_buffer){
	//draws shark's body
	alt_up_pixel_buffer_dma_draw_box(pixel_buffer, body_pos[0], body_pos[1], body_pos[2], body_pos[3], colour, 0);

}

void draw_cursor(int pos[], int colour, alt_up_pixel_buffer_dma_dev* pixel_buffer){
	//draws cursor
	alt_up_pixel_buffer_dma_draw_box(pixel_buffer, pos[0], pos[1], pos[2], pos[3], colour, 0);

}


